name: "Propose a Primer pattern or component"
description: Suggest a new pattern or component, or an update to an existing one
title: "[Proposal] featureName"
labels: ["design", "proposal", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Start here
        1. Replace featureName in the title with the name of your feature or project.
        2. Before you submit this issue, make sure you've read the [Handling new patterns documentation](https://primer.style/design/guides/contribute/handling-new-patterns).

  - type: dropdown
    attributes:
      label: Primer or Primer Brand?
      options:
        - Primer
        - Primer Brand
    validations:
      required: true
  - type: dropdown
    attributes:
      label: This proposal is concerning a
      description:
      options:
        - New pattern idea
        - Nomination of a shared component for upstreaming
        - Modification to an existing Primer pattern
    validations:
      required: true
  - type: input
    attributes:
      label: Team working on this feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the pattern or pattern updates you are proposing
      description: Please add a brief description of the pattern or the updates needed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Where will the pattern be used, or is already used?
      description: In what use cases will the pattern be useful, or, in case of existing patterns, where is it used now? If known, indicate if the pattern will be needed across different implementations and why/why not. Include links and screenshots, if possible.
  - type: textarea
    attributes:
      label: Why is this pattern needed?
      description: Please add a brief description of why you believe this pattern or component should exist in Primer. For example, to support a new feature, to improve the developer experience, to improve the user experience in a certain way.
  - type: textarea
    attributes:
      label: Are there sketches, wireframes, mockups, or prototypes?
      description: Include links to anything that can help visualise and understand the proposal. If the files are very big and complex, please link to the relevant views, and/or add a description of what we should focus on.
  - type: textarea
    attributes:
      label: Is this pattern needed for a launch event or other deadline? Is this pattern critical to the success of a feature ship?
      description: Please include details of how this pattern is relevant to your success, and whether it's connected to a launch event. Include deadlines, team OKRs, planning, whatever helps us to prioritize this work.
  - type: textarea
    attributes:
      label: Do you have design and/or engineering resources available to work on this? Or are you requesting the Primer team to take on the full scope of work?
      description: Is there a team available (now or in the near future) to work on the design and implementation of this pattern. If so, please provide details about who is/will be available.
  - type: textarea
    attributes:
      label: What other ways (if any) might you be able to achieve your goals if we can't complete this work in your timeframe?
      description: What's your plan B?
  - type: textarea
    attributes:
      label: Additional context
      description: Include any dependencies, and links with relevant information like, research, specs, Figma links, code prototypes, discussion threads, related issues, previous work, etc.
